# NPZ File Viewer

In [1]:
import numpy as np

data = np.load(
    "/u6/cjrisi/rl-insulin-pump/runs/watgpu-partition_test-configs_20250716_000036/logs/evaluations.npz"
)
print(data.files)  # Lists all arrays stored in the file

for key in data.files:
    print(f"{key}:")
    print(data[key])

['timesteps', 'results', 'ep_lengths']
timesteps:
[ 5000 10000]
results:
[[97.517972 99.175452 98.590801 99.589002 99.812686]
 [99.211344 99.153253 98.179166 98.761677 98.400856]]
ep_lengths:
[[490 196 157 403 517]
 [505 500 124 597 595]]
